db_root_password: "{{secrets_db_root_pass}}"

db_host: "{{hostvars[groups.controller_nodes[0]].ansible_fqdn}}"
keystone_host: "{{hostvars[groups.controller_nodes[0]].ansible_fqdn}}"
glance_host: "{{hostvars[groups.controller_nodes[0]].ansible_fqdn}}"
