ansible_version_min: 2.11.0
management_interface: "{{ansible_default_ipv4.interface}}"

db_root_password: "{{secrets_db_root_pass}}"

os_region: RegionOne
os_availability_zone: nova

ca_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"
db_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"
memcached_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"
rabbitmq_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"
logging_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"
neutron_nova_metadata_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"

keystone_url: "https://{{hostvars[groups.controller_nodes[0]].ansible_nodename}}:5000"
glance_url: "http://{{hostvars[groups.controller_nodes[0]].ansible_nodename}}:9292"
neutron_url: "http://{{hostvars[groups.controller_nodes[0]].ansible_nodename}}:9696"
nova_novnc_url: "https://{{hostvars[groups.controller_nodes[0]].ansible_nodename}}:6080"

is_controller_node: "{{'controller_nodes' in group_names}}"
is_compute_node: "{{'compute_nodes' in group_names}}"
is_block_storage_node: "{{'block_storage_nodes' in group_names}}"
is_network_node: "{{'network_nodes' in group_names}}"

package_state: present
