- name: init database
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: octavia
    db_user: octavia
    db_user_password: "{{octavia_db_user_password}}"

- name: init keystone octavia service
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: octavia
    keystone_user_password: "{{octavia_user_password}}"
    keystone_service_name: octavia
    keystone_service_description: OpenStack Octavia
    keystone_service_type: load-balancer
    keystone_service_url: "{{octavia_url}}"
    keystone_service_path: /
  when: is_controller_node

- name: create env file for maintaining
  template:
    src: octavia-openrc.j2
    dest: ~/octavia-openrc
    mode: 0600
  become: false

- name: create amphora ssh key
  openssh_keypair:
    path: ~/.ssh/octavia_amphora_id_rsa
    size: 4096
    mode: 0600
  become: false
  register: octavia_amphora_ssh_key
  when: octavia_management_ssh

- name: create amphora key pair
  os_keypair:
    auth: "{{octavia_keystone_auth}}"
    name: amphora
    public_key_file: "{{octavia_amphora_ssh_key.filename}}.pub"
  when: octavia_management_ssh

- name: add amphora flavor
  os_nova_flavor:
    auth: "{{octavia_keystone_auth}}"
    flavorid: "200"
    name: amphora
    vcpus: "1"
    ram: "1024"
    disk: "2"
    is_public: false
