- name: create security group for management
  os_security_group:
    auth: "{{octavia_keystone_auth}}"
    name: octavia-lb-mgmt
    description: "Octavia Load Balancer management"

- name: add rule for icmp
  os_security_group_rule:
    auth: "{{octavia_keystone_auth}}"
    security_group: octavia-lb-mgmt
    protocol: icmp
    remote_ip_prefix: "{{octavia_management_subnet}}"

- name: add rule for ssh
  os_security_group_rule:
    auth: "{{octavia_keystone_auth}}"
    security_group: octavia-lb-mgmt
    protocol: tcp
    port_range_min: "22"
    port_range_max: "22"
    remote_ip_prefix: "{{octavia_management_subnet}}"
    state: "{{ 'present' if octavia_management_ssh else 'absent'}}"

- name: add rule for alt https
  os_security_group_rule:
    auth: "{{octavia_keystone_auth}}"
    security_group: octavia-lb-mgmt
    protocol: tcp
    port_range_min: "9443"
    port_range_max: "9443"
    remote_ip_prefix: "{{octavia_management_subnet}}"

- name: create security group for health manager
  os_security_group:
    auth: "{{octavia_keystone_auth}}"
    name: octavia-lb-health-mgr
    description: "Octavia Load Balancer health manager"

- name: add rule for health
  os_security_group_rule:
    auth: "{{octavia_keystone_auth}}"
    security_group: octavia-lb-health-mgr
    protocol: udp
    port_range_min: "5555"
    port_range_max: "5555"
    remote_ip_prefix: "{{octavia_management_subnet}}"

- name: create management network
  os_network:
    auth: "{{octavia_keystone_auth}}"
    name: octavia-lb-mgmt
    region_name: "{{os_region}}"

- name: fetch management network id
  shell: |
    . {{ansible_env.PWD}}/octavia-openrc
    openstack network show octavia-lb-mgmt -c id -f value
  changed_when: false
  check_mode: false
  register: octavia_management_network

- name: create management subnet
  os_subnet:
    auth: "{{octavia_keystone_auth}}"
    network_name: octavia-lb-mgmt
    name: octavia-lb-mgmt
    cidr: "{{octavia_management_subnet}}"
    no_gateway_ip: true
    allocation_pool_start: "{{octavia_management_subnet | ansible.netcommon.ipaddr('next_usable')}}"
    allocation_pool_end: "{{octavia_management_subnet | ansible.netcommon.ipaddr('last_usable')}}"
