- name: install
  apt:
    name: chrony

- name: configure
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
  notify: restart chrony

- name: enable
  systemd:
    name: chrony
    enabled: true

- name: flush handlers
  meta: flush_handlers
