- name: install
  yum:
    name: chrony

- name: configure
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: restart chrony

- name: start and enable
  systemd:
    name: chronyd
    state: started
    enabled: true

- name: flush handlers
  meta: flush_handlers
