- name: init magnum db
  shell: su -s /bin/sh -c "magnum-db-manage upgrade" magnum

- name: restart magnum-api
  systemd:
    name: openstack-magnum-api
    state: restarted

- name: restart magnum-conductor
  systemd:
    name: openstack-magnum-conductor
    state: restarted

- name: restart magnum registry
  systemd:
    name: registry
    state: restarted
    daemon_reload: true
