- name: init database
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: glance
    db_user: glance
    db_user_password: "{{glance_db_user_password}}"

- name: init keystone
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: glance
    keystone_user_password: "{{glance_user_password}}"
    keystone_service_name: glance
    keystone_service_description: OpenStack Image
    keystone_service_type: image
    keystone_service_url: "http://{{ansible_nodename}}:9292"

- name: install
  yum:
    name: openstack-glance

- name: configure api
  template:
    src: api.conf.j2
    dest: /etc/glance/glance-api.conf
    backup: true
  notify:
    - init glance db
    - restart glance-api

- name: configure registry
  template:
    src: registry.conf.j2
    dest: /etc/glance/glance-registry.conf
    backup: true
  notify: restart glance-registry

- name: setup backend
  include_tasks: "backends/{{glance_backend}}.yml"

- name: flush handlers
  meta: flush_handlers

- name: start and enable
  systemd:
    name: "{{item}}"
    state: started
    enabled: true
  loop:
    - openstack-glance-registry
    - openstack-glance-api
