- name: init database
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: glance
    db_user: glance
    db_user_password: "{{glance_db_user_password}}"

- name: init keystone
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: glance
    keystone_user_password: "{{glance_user_password}}"
    keystone_service_name: glance
    keystone_service_description: OpenStack Image
    keystone_service_type: image
    keystone_service_url: "{{glance_url}}"

- name: install
  package:
    name: openstack-glance
    state: "{{package_state | default('present')}}"
  notify:
    - init glance db
    - restart glance-api
    - restart glance-registry

- name: configure api
  template:
    src: api.conf.j2
    dest: /etc/glance/glance-api.conf
    backup: true
  notify:
    - init glance db
    - restart glance-api

- name: setup backend
  include_tasks: "backends/{{glance_backend}}.yml"

- name: start and enable glance-api
  systemd:
    name: openstack-glance-api
    state: started
    enabled: true

# glance-registry is deprecated
- name: configure registry
  template:
    src: registry.conf.j2
    dest: /etc/glance/glance-registry.conf
    backup: true
  notify: restart glance-registry
  when: ansible_distribution_major_version|int < 8

- name: start and enable glance-registry
  systemd:
    name: openstack-glance-registry
    state: started
    enabled: true
  when: ansible_distribution_major_version|int < 8

- name: flush handlers
  meta: flush_handlers
