- name: init database
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: cinder
    db_user: cinder
    db_user_password: "{{cinder_db_user_password}}"
  run_once: true

- name: init keystone v2
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: cinder
    keystone_user_password: "{{cinder_user_password}}"
    keystone_service_name: cinderv2
    keystone_service_description: OpenStack Block Storage
    keystone_service_type: volumev2
    keystone_service_url: "{{cinder_url}}/v2/%(project_id)s"

- name: init keystone v3
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: cinder
    keystone_user_password: "{{cinder_user_password}}"
    keystone_service_name: cinderv3
    keystone_service_description: OpenStack Block Storage
    keystone_service_type: volumev3
    keystone_service_url: "{{cinder_url}}/v3/%(project_id)s"
