- name: install
  yum:
    name: 
      - openstack-cinder
      - python-keystone
  when: is_block_storage_node or is_controller_node

- name: configure controller
  import_tasks: controller.yml
  when: is_controller_node

- name: configure
  template:
    src: cinder.conf.j2
    dest: /etc/cinder/cinder.conf
    backup: true
  notify:
    - init cinder db
    - restart cinder-api
    - restart cinder-scheduler
    - restart cinder-volume
  when: is_block_storage_node or is_controller_node

- name: configure lvm backend
  include_tasks: "backends/lvm.yml"
  when: "is_block_storage_node
        and cinder_backend == 'lvm'"

- name: configure rbd backend
  include_tasks: backends/rbd.yml
  when: "(is_block_storage_node or is_compute_node)
        and cinder_backend == 'rbd'"

- name: flush handlers
  meta: flush_handlers

- name: start and enable api and scheduler service
  systemd:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - openstack-cinder-api
    - openstack-cinder-scheduler
  when: is_controller_node

- name: start and enable volume service
  systemd:
    name: openstack-cinder-volume
    enabled: true
    state: started
  when: is_block_storage_node
