- name: configure controller
  import_tasks: controller.yml
  when: "'controller_nodes' in group_names"

- name: configure storage node
  import_tasks: storage_node.yml
  when: "'block_storage_nodes' in group_names"

- name: flush handlers
  meta: flush_handlers

- name: start and enable api and scheduler service
  systemd:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - openstack-cinder-api
    - openstack-cinder-scheduler
  when: "'controller_nodes' in group_names"

- name: start and enable volume service
  systemd:
    name: openstack-cinder-volume
    enabled: true
    state: started
  when: "'block_storage_nodes' in group_names"
