- name: install
  apt:
    name: "{{item}}"
  loop:
    - cinder-volume
    - lvm2
    - thin-provisioning-tools

- name: patition disk
  parted:
    device: "{{item}}"
    number: 1
    state: present
  loop: "{{cinder_drives}}"

- name: create filesystem
  filesystem:
    device: "{{item}}1"
    fstype: lvm
    opts: -L cinder-volumes
  loop: "{{cinder_drives}}"

- name: create volume group
  lvg:
    vg: cinder-volumes
    pvs: "{{cinder_drives | map('regex_replace', '$', '1') | list | join(',')}}"

- name: configure
  template:
    src: storage_node.conf.j2
    dest: /etc/cinder/cinder.conf
    backup: true
  notify: 
    - restart tgt
    - restart cinder-volume
