- name: install
  yum:
    name: 
      - openstack-cinder
      - python-keystone

- name: configure
  template:
    src: storage_node.conf.j2
    dest: /etc/cinder/cinder.conf
    backup: true
  notify: restart cinder-volume

- name: configure backend
  include_tasks: "backends/{{cinder_backend}}.yml"
