- name: install rpm key
  rpm_key:
    key: https://packages.grafana.com/gpg.key

- name: add repo
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: install
  yum:
    name: grafana

- name: configure
  template:
    src:  "{{item.src}}.j2"
    dest: "{{item.dest}}"
  loop:
    - src: grafana.ini
      dest: /etc/grafana/grafana.ini
    - src: datasources.yml
      dest: /etc/grafana/provisioning/datasources/openstack.yml
    - src: dashboards.yml
      dest: /etc/grafana/provisioning/dashboards/openstack.yml
  notify: restart grafana

- name: configure grafana httpd
  template:
    src: grafana.conf.j2
    dest: /etc/httpd/conf.d/grafana.conf
  notify: reload httpd

- name: create dashboards folder
  file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: get dashboards
  include_tasks: dashboard.yml
  loop: "{{grafana_dashboards}}"

- name: flush handlers
  meta: flush_handlers

- name: start and enable
  systemd:
    name: grafana-server
    state: started
    enabled: true
