all:
  hosts:
    controller:
      ansible_host: 10.64.1.50
    compute1:
      ansible_host: 10.64.1.51
      provider_interface: eno2
      cinder_pools:
        - type: ssd
          members:
            - /dev/sda2
        - type: msd
          members:
            - /dev/sdb1
    compute2:
      ansible_host: 10.64.1.52
      provider_interface: eno2
      cinder_pools:
        - type: ssd
          members:
            - /dev/sda2
    compute3:
      ansible_host: 10.64.1.53
      provider_interface: enp3s0
      cinder_pools:
        - type: ssd
          members:
            - /dev/sda3
        - type: msd
          members:
            - /dev/sdb1
  children:
    nodes:
      children:
        controller_nodes:
          hosts:
            controller:
        compute_nodes:
          hosts:
            compute1:
            compute2:
            compute3:
        block_storage_nodes:
          hosts:
            compute1:
            compute2:
            compute3:
        object_storage_nodes:
          hosts:
            compute1:
