all:
  hosts:
    controller1:
      ansible_host: openstack-controller1.virt.home.zotha.de
      management_interface: eth0
    compute1:
      ansible_host: openstack-compute1.virt.home.zotha.de
      management_interface: eno1
      provider_interface: eno2
  children:
    nodes:
      children:
        controller_nodes:
          hosts:
            controller1:
        compute_nodes:
          hosts:
            compute1:
        block_storage_nodes:
          hosts:
            compute1:
        object_storage_nodes:
          hosts:
            compute1:
