all:
  hosts:
    controller:
      ansible_host: 10.64.1.50
    compute1:
      ansible_host: 10.64.1.51
  children:
    nodes:
      children:
        controller_nodes:
          hosts:
            controller:
        compute_nodes:
          hosts:
            compute1:
        block_storage_nodes:
          hosts:
            compute1:
        object_storage_nodes:
          hosts:
            compute1:
