- name: openstack
  hosts: nodes
  become: true
  vars_files:
    - vars/secrets.yml
  pre_tasks:
    - name: set management_ipv4
      set_fact:
        management_ipv4: "{{hostvars[inventory_hostname]['ansible_' + management_interface].ipv4}}"
      tags:
        - always
  roles:
    # environment services
    - role: bootstrap
      tags: bootstrap
    - role: ca
      tags: ca
    - role: ntp
      tags: ntp
    - role: mariadb
      tags: db,mariadb,mysql
      when: is_controller_node
    - role: rabbitmq
      tags: rabbit,rabbitmq
      when: is_controller_node
    - role: memcached
      tags: memcached
      when: is_controller_node
    - role: etcd
      tags: etcd
      when: is_controller_node

    # openstack services
    - role: keystone
      tags: keystone
      when: is_controller_node
    - role: glance
      tags: glance
      when: is_controller_node
    - role: placement
      tags: placement
      when: is_controller_node
    - role: nova
      tags: nova
      when: is_controller_node 
            or is_compute_node
    - role: neutron
      tags: neutron
      when: "is_network_node 
            or is_compute_node"
    - role: cinder
      tags: cinder
      when: is_controller_node 
            or is_compute_node 
            or is_block_storage_node
    # - role: heat
    #   tags: heat
    #   when: is_controller_node
    - role: horizon
      tags: horizon
      when: is_controller_node
