- name: openstack
  hosts: openstack
  become: true
  pre_tasks:
    - name: set management_ipv4
      set_fact:
        management_ipv4: "{{hostvars[inventory_hostname]['ansible_' + management_interface].ipv4}}"
      tags:
        - always
  roles:
    # environment services
    - role: bootstrap
      tags: environment,bootstrap
    - role: ca
      tags: environment,ca
    - role: ntp
      tags: environment,ntp
    - role: mariadb
      tags: environment,db,mariadb,mysql
      when: is_controller_node
    - role: memcached
      tags: environment,memcached
      when: is_controller_node
    # - role: etcd
    #   tags: environment,etcd
    #   when: is_controller_node
    - role: httpd
      tags: environment,httpd
      when: is_controller_node
    - role: rabbitmq
      tags: environment,rabbit,rabbitmq
      when: is_controller_node
    - role: traefik
      tags: environment,traefik,lb
      when: is_controller_node
            and traefik_enabled | default(false)

    # openstack services
    - role: keystone
      tags: openstack,keystone
      when: is_controller_node
    - role: glance
      tags: openstack,glance
      when: is_controller_node
    - role: placement
      tags: openstack,placement
      when: is_controller_node
    - role: nova
      tags: openstack,nova
      when: is_controller_node
            or is_compute_node
    - role: neutron
      tags: openstack,neutron
      when: is_controller_node
            or is_network_node
            or is_compute_node
    - role: cinder
      tags: openstack,cinder
      when: is_controller_node
            or is_compute_node
            or is_block_storage_node
    - role: heat
      tags: openstack,heat
      when: is_controller_node
    - role: horizon
      tags: openstack,horizon
      when: is_controller_node

    # optional openstack services
    - role: magnum
      tags: openstack,magnum
      when: is_controller_node
            and magnum_enabled | default(false)
    - role: designate
      tags: openstack,designate
      when: is_controller_node
            and designate_enabled | default(false)
    - role: trove
      tags: openstack,trove
      when: is_controller_node
            and trove_enabled | default(false)
    - role: swift-ceph
      tags: openstack,swift-ceph
      when: is_controller_node
            and swift_ceph_enabled | default(false)

    # logging services
    - role: loki
      tags: logging,loki
      when: is_controller_node
    - role: fluentd
      tags: logging,fluentd
    - role: prometheus
      tags: monitoring,prometheus
      when: is_controller_node
    - role: node-exporter
      tags: monitoring,node-exporter
    - role: grafana
      tags: monitoring,grafana
      when: is_controller_node
