- name: openstack
  hosts: nodes
  become: true
  vars_files:
    - vars/secrets.yml
  pre_tasks:
    - name: set management_ipv4
      set_fact:
        management_ipv4: "{{hostvars[inventory_hostname]['ansible_' + management_interface].ipv4}}"
      tags:
        - always
  roles:
    # environment services
    - role: bootstrap
      tags: bootstrap
    - role: ntp
      tags: ntp
    - role: mariadb
      tags: db,mariadb,mysql
      when: "'controller_nodes' in group_names"
    - role: rabbitmq
      tags: rabbit,rabbitmq
      when: "'controller_nodes' in group_names"
    - role: memcached
      tags: memcached
      when: "'controller_nodes' in group_names"
    - role: etcd
      tags: etcd
      when: "'controller_nodes' in group_names"

    # openstack services
    - role: keystone
      tags: keystone
      when: "'controller_nodes' in group_names"
    - role: glance
      tags: glance
      when: "'controller_nodes' in group_names"
    - role: placement
      tags: placement
      when: "'controller_nodes' in group_names"
    - role: nova
      tags: nova
    - role: neutron
      tags: neutron
    - role: cinder
      tags: cinder
    # - role: heat
    #   tags: heat
    #   when: "'controller_nodes' in group_names"
    - role: horizon
      tags: horizon
      when: "'controller_nodes' in group_names"
