- name: install lvm requirements
  yum:
    name:
    - lvm2
    - device-mapper-persistent-data
    - targetcli

- name: prepare vg
  include_tasks: prepare_vg.yml
  loop: "{{cinder_lvm_pools}}"
  loop_control:
    loop_var: pool

- name: create filesystem
  filesystem:
    device: "{{item}}"
    fstype: lvm
  loop: "{{pool.members}}"

- name: create volume group
  lvg:
    vg: "cinder-{{pool.type}}"
    pvs: "{{pool.members | join(',')}}"

- name: configure lvm filter
  lineinfile:
    path: /etc/lvm/lvm.conf
    insertafter: '# filter ='
    regexp: "^\tfilter ="
    line: "\tfilter = [ \"a|^/dev/sd[a-z][0-9]$|\", \"r/.*/\" ]"
  when: "is_block_storage_node 
          or is_compute_node"

- name: start and enable lvmetad and target service
  systemd:
    name: target
    enabled: true
    state: started
  loop:
    - lvm2-lvmetad
    - target
