- name: install lvm requirements
  yum:
    name:
    - lvm2
    - device-mapper-persistent-data
    - targetcli
  when: is_block_storage_node

- name: configure lvm filter
  lineinfile:
    path: /etc/lvm/lvm.conf
    insertafter: '# filter ='
    regexp: "^\tfilter ="
    line: "\tfilter = [ {{cinder_lvm_filter}} ]"
  when: "is_block_storage_node 
          or is_compute_node"

- name: start and enable lvmetad and target service
  systemd:
    name: target
    enabled: true
    state: started
  loop:
    - lvm2-lvmetad
    - target
  when: is_block_storage_node
