- name: install rbd requirements
  package:
    name:
      - "{{'python' if ansible_distribution_major_version|int < 8 else 'python3'}}-rbd"
      - "{{'python' if ansible_distribution_major_version|int < 8 else 'python3'}}-rados"
      - ceph-common

- name: add user to ceph group
  user:
    name: cinder
    groups: ceph
    append: true
  when: is_block_storage_node

- name: fetch ceph key
  slurp:
    path: "{{cinder_rbd_keyring}}"
  register: cinder_rbd_client_key
  when: is_compute_node

- name: create libvirt rbd secret
  template:
    src: libvirt_cinder_ceph.xml.j2
    dest: /etc/ceph/libvirt_cinder_ceph.xml
  notify: define cinder ceph secret
  when: is_compute_node
