- name: install rbd requirements
  yum:
    name:
    - python-rbd
    - python-rados
    - ceph-common

- name: check ceph keyring
  file:
    path: "{{cinder_rbd_keyring}}"
    mode: 0640
    group: cinder
  when: is_block_storage_node

- name: set keyring in ceph config
  blockinfile:
    path: /etc/ceph/ceph.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - cinder"
    block: |
      [client.cinder]
      keyring = {{cinder_rbd_keyring}}
  when: is_block_storage_node

- name: fetch ceph key
  slurp:
    path: "{{cinder_rbd_keyring}}"
  register: cinder_rbd_client_key
  when: is_compute_node

- name: create libvirt rbd secret
  template:
    src: libvirt_cinder_ceph.xml.j2
    dest: /etc/ceph/libvirt_cinder_ceph.xml
  notify: define cinder ceph secret
  when: is_compute_node
