- name: install rbd requirements
  yum:
    name:
    - python-rbd
    - python-rados
    - ceph-common

- name: create ceph directory
  file:
    path: /etc/ceph
    state: directory

- name: copy ceph config
  copy:
    src: ceph.conf
    dest: /etc/ceph/ceph.conf

- name: copy ceph keyring
  template:
    src: ceph.client.cinder.keyring.j2
    dest: /etc/ceph/ceph.client.cinder.keyring
    mode: 0640
    group: cinder
  when: is_block_storage_node

- name: create libvirt rbd secret
  template:
    src: libvirt_ceph.xml.j2
    dest: /etc/ceph/libvirt_ceph.xml
  notify: define ceph secret
  when: is_compute_node
