- name: install rbd requirements
  yum:
    name:
    - python-rbd
    - python-rados
    - ceph-common

- name: check ceph keyring
  file:
    path: "{{cinder_rbd_keyring_conf}}"
    mode: 0640
    group: cinder
  when: is_block_storage_node

- name: fetch ceph key
  slurp:
    path: "{{cinder_rbd_keyring_conf}}"
  register: cinder_rbd_client_key
  when: is_compute_node

- name: create libvirt rbd secret
  template:
    src: libvirt_ceph.xml.j2
    dest: /etc/ceph/libvirt_ceph.xml
  notify: define ceph secret
  when: is_compute_node
