- name: install rpm key
  rpm_key:
    key: https://packages.treasuredata.com/GPG-KEY-td-agent

- name: add repo
  template:
    src: fluentd.repo.j2
    dest: /etc/yum.repos.d/fluentd.repo

- name: install
  yum:
    update_cache: true
    name: td-agent

- name: configure
  template:
    src: fluent.conf.j2
    dest: /etc/td-agent/td-agent.conf
  notify:
    - install fluent plugins
    - restart fluentd

- name: add user to groups (controller node)
  user:
    name: td-agent
    groups: root,keystone,nova,neutron,cinder,glance,magnum,placement
    append: true
  when: is_controller_node

- name: add user to groups (compute node)
  user:
    name: td-agent
    groups: root,nova,neutron
    append: true
  when: is_compute_node

- name: add user to groups (block storage node)
  user:
    name: td-agent
    groups: root,cinder
    append: true
  when: is_block_storage_node

- name: add user to groups (network node)
  user:
    name: td-agent
    groups: root,neutron
    append: true
  when: is_network_node

- name: flush handlers
  meta: flush_handlers

- name: start and enable
  systemd:
    name: td-agent
    state: started
    enabled: true

