- name: install rpm key
  rpm_key:
    key: https://packages.treasuredata.com/GPG-KEY-td-agent

- name: add repo
  template:
    src: fluentd.repo.j2
    dest: /etc/yum.repos.d/fluentd.repo

- name: install
  package:
    update_cache: true
    name: td-agent

- name: configure
  template:
    src: fluent.conf.j2
    dest: /etc/td-agent/td-agent.conf
  notify:
    - install fluent plugins
    - restart fluentd

- name: set directory acls
  include_tasks: acl_directory.yml
  loop: "{{fluentd_log_directories}}"

- name: set file acls
  include_tasks: acl_file.yml
  loop: "{{fluentd_log_files}}"

- name: flush handlers
  meta: flush_handlers

- name: start and enable
  systemd:
    name: td-agent
    state: started
    enabled: true
