- name: install rpm key
  rpm_key:
    key: https://packages.treasuredata.com/GPG-KEY-td-agent

- name: add repo
  template:
    src: fluentd.repo.j2
    dest: /etc/yum.repos.d/fluentd.repo

- name: install
  yum:
    update_cache: true
    name: td-agent

- name: configure
  template:
    src: fluent.conf.j2
    dest: /etc/td-agent/td-agent.conf
  notify:
    - install fluent plugins
    - restart fluentd

- name: get available groups
  getent:
    database: group

- name: add user to service groups
  user:
    name: td-agent
    groups: "{{item}}"
    append: true
  when: item in ansible_facts.getent_group
  loop:
    - root
    - keystone
    - nova
    - neutron
    - cinder
    - glance
    - placement
    - magnum
    - designate
    - heat

- name: flush handlers
  meta: flush_handlers

- name: start and enable
  systemd:
    name: td-agent
    state: started
    enabled: true

