keystone_admin_password: "{{secrets_admin_pass}}"
keystone_db_user_password: "{{secrets_keystone_dbpass}}"
keystone_host: "{{hostvars[groups.controller_nodes[0]].ansible_fqdn}}"

keystone_admin_auth:
  auth_url: https://{{keystone_host}}:5000/v3
  username: admin
  password: "{{keystone_admin_password}}"
  user_domain_name: Default
  project_domain_name: Default
  project_name: admin
