keystone_admin_password: "{{secrets_admin_pass}}"
keystone_db_user_password: "{{secrets_keystone_dbpass}}"
keystone_url: "https://{{ansible_nodename}}:5000"
keystone_admin_url: "{{keystone_url}}"
keystone_public_url: "{{keystone_url}}"
keystone_bootstrap_region: "{{os_region}}"
keystone_token_expiration: 3600
keystone_freeipa_servers: []
  # - domain: example
  #   # freeipa uses tls, so make sure you add the ca certificate to trust anchors
  #   url: ldap://ipa1.example.com
  #   user: uid=openstack,cn=users,cn=accounts,dc=example,dc=com
  #   password: "{{secrets_ldap_pass}}"
  #   suffix: dc=example,dc=com
  #   user_filter: (memberof=cn=openstack-users,cn=groups,cn=accounts,dc=example,dc=com)
  #   group_filter: ""

keystone_admin_auth:
  auth_url: "{{keystone_url}}/v3"
  username: admin
  password: "{{keystone_admin_password}}"
  user_domain_name: Default
  project_domain_name: Default
  project_name: admin

keystone_service_endpoint_interfaces:
  - public
  - internal
  - admin

keystone_service_public_url: {}
  # <service_name>: <url>
keystone_service_admin_url: {}
  # <service_name>: <url>
