horizon_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"
horizon_secret_key: "{{secrets_horizon_secret}}"
horizon_allowed_hosts:
  - "{{ansible_nodename}}"
horizon_physical_networks:
  - provider
horizon_session_timeout: 3600
