horizon_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"
horizon_secret_key: "{{secrets_horizon_secret}}"
horizon_allowed_hosts:
  - "{{ansible_nodename}}"
horizon_physical_networks:
  - provider
horizon_session_timeout: 3600


# customize the dashboard: https://docs.openstack.org/horizon/latest/admin/customize-configure.html
horizon_customize_site_branding: ~ # Example, Inc. Cloud
horizon_customize_site_branding_link: ~ # http://example.com
horizon_customize_help_url: ~ # http://openstack.mycompany.org

# specify file to override the default OpenStack logo in the upper left corner in the Horizon Dashboard
# you should use svg, as the name of the file will be ".../logo.svg"
horizon_custom_logo_file: ~
# specify file to override the default OpenStack logo on the login screen
# you should use svg, as the name of the file will be ".../logo-splash.svg"
horizon_custom_logo_splash_file: ~
