- name: install rpm key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: add repo
  template:
    src: elk.repo.j2
    dest: /etc/yum.repos.d/elk.repo

- name: install
  yum:
    update_cache: true
    name: 
      - elasticsearch
      - kibana

- name: configure elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: configure kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: restart kibana

- name: configure kibana htpasswd
  htpasswd:
    path: /etc/httpd/kibana.htpasswd
    name: "{{ kibana_user }}"
    password: "{{ secrets_kibana_pass }}"
    owner: apache
    mode: 0640

- name: configure kibana httpd
  template:
    src: kibana3.conf.j2
    dest: /etc/httpd/conf.d/kibana3.conf
  notify: reload httpd

- name: start and enable
  systemd:
    name: "{{item}}"
    state: started
    enabled: true
  loop:
    - elasticsearch
    - kibana

- name: flush handlers
  meta: flush_handlers
