nova_db_user_password: "{{secrets_nova_dbpass}}"
nova_user_password: "{{secrets_nova_pass}}"
nova_placement_user_password: "{{secrets_placement_pass}}"
nova_db_placement_user_password: "{{secrets_placement_dbpass}}"
nova_rabbitmq_user: openstack
nova_rabbitmq_user_password: "{{secrets_rabbit_pass}}"
nova_ip_address: "{{management_ipv4.address}}"
nova_neutron_user_password: "{{secrets_neutron_pass}}"
nova_metadata_secret: "{{secrets_metadata_secret}}"
nova_ephemeral_storage_backend: local # local and rbd are supported 
nova_rbd_ceph_conf: /etc/ceph/ceph.conf
nova_rbd_keyring_conf: /etc/ceph/ceph.client.nova.keyring
nova_rbd_user: nova
nova_rbd_secret_uuid: D618BD91-40DF-4AC3-9EDE-076786714761
nova_rbd_pool: vms
nova_libvirt_cpu_mode: host-model
nova_libvirt_cpu_model_extra_flags: null
nova_nested_guest_support: false

nova_url: "http://{{ansible_nodename}}:8774"
nova_novnc_url: "https://{{ansible_nodename}}:6080"

nova_flavors:
  - name: m1.tiny
    vcpus: 1
    disk: 1
    ram: 512
  - name: m1.small
    vcpus: 1
    disk: 20
    ram: 2048
  - name: m1.medium
    vcpus: 2
    disk: 40
    ram: 4096
  - name: m1.large
    vcpus: 4
    disk: 80
    ram: 8192
  - name: m1.xlarge
    vcpus: 8
    disk: 160
    ram: 16384
