nova_db_root_password: "{{secrets_db_root_pass}}"
nova_db_user_password: "{{secrets_nova_dbpass}}"
nova_db_host: "{{hostvars[groups.controller_nodes[0]].inventory_hostname}}"
nova_user_password: "{{secrets_nova_pass}}"
nova_keystone_host: "{{hostvars[groups.controller_nodes[0]].inventory_hostname}}"
nova_placement_user_password: "{{secrets_placement_pass}}"
nova_db_placement_user_password: "{{secrets_placement_dbpass}}"
nova_rabbitmq_user: openstack
nova_rabbitmq_user_password: "{{secrets_rabbit_pass}}"
nova_rabbitmq_host: "{{hostvars[groups.controller_nodes[0]].inventory_hostname}}"
nova_memcached_host: "{{hostvars[groups.controller_nodes[0]].inventory_hostname}}"
nova_ip_address: "{{management_ip_address}}"
nova_neutron_user_password: "{{secrets_neutron_pass}}"
nova_metadata_secret: "{{secrets_metadata_secret}}"
nova_neutron_host: "{{hostvars[groups.controller_nodes[0]].inventory_hostname}}"
nova_glance_api_host: "{{hostvars[groups.controller_nodes[0]].inventory_hostname}}"
nova_novnc_host: "{{hostvars[groups.controller_nodes[0]].inventory_hostname}}"
