nova_db_user_password: "{{secrets_nova_dbpass}}"
nova_user_password: "{{secrets_nova_pass}}"
nova_placement_user_password: "{{secrets_placement_pass}}"
nova_db_placement_user_password: "{{secrets_placement_dbpass}}"
nova_rabbitmq_user: openstack
nova_rabbitmq_user_password: "{{secrets_rabbit_pass}}"
nova_ip_address: "{{management_ipv4.address}}"
nova_neutron_user_password: "{{secrets_neutron_pass}}"
nova_metadata_secret: "{{secrets_metadata_secret}}"
nova_novnc_host: "{{hostvars[groups.controller_nodes[0]].ansible_fqdn}}"
