- name: install fluent plugins
  shell: |
    /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch
    /usr/sbin/td-agent-gem install fluent-plugin-add

- name: restart fluentd
  systemd:
    name: td-agent
    state: restarted

