- name: install
  yum:
    name: rabbitmq-server

- name: start and enable
  systemd:
    name: rabbitmq-server
    state: started
    enabled: true

- name: add user
  rabbitmq_user:
    user: "{{rabbitmq_user}}"
    password: "{{rabbitmq_user_password}}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
