# renovate: datasource=github-tags depName=traefik/traefik versioning=semver-coerced
traefik_version: 2.11.6
# log level can be DEBUG, PANIC, FATAL, ERROR, WARN or INFO
traefik_log_level: ERROR
traefik_admin_domain: null
traefik_public_domain: example.com
traefik_controller_domain: "controller.{{traefik_public_domain}}"
traefik_httpd_url: http://localhost:8081
# skip ssl verification for backends
traefik_insecure_skip_verify: true
# default is admin / admin
traefik_dashboard_users:
  - admin:$apr1$bpcAEgIt$jdv/yN9/LyKWZwxbbmyA2/
traefik_acme: false
traefik_acme_email: admin@example.com
# for production change this to https://acme-v02.api.letsencrypt.org/directory
traefik_acme_ca_server: https://acme-staging-v02.api.letsencrypt.org/directory
traefik_acme_dns_challenge_provider: cloudflare
traefik_acme_dns_challenge_disable_propagation_check: false
traefik_acme_dns_challenge_resolvers: []
traefik_secrets: []
  # - CF_DNS_API_TOKEN=secret

traefik_services:
  - name: keystone
    url: https://localhost:5000
  - name: glance
    url: http://localhost:9292
  - name: placement
    url: http://localhost:8778
  - name: nova
    url: http://localhost:8774
  - name: nova-novnc
    url: https://localhost:6080
    enable_websockets: true
  - name: neutron
    url: http://localhost:9696
  - name: cinder
    url: http://localhost:8776
  - name: heat
    url: http://localhost:8004
  - name: heat-cfn
    url: http://localhost:8000

traefik_additional_services: []
