- name: configure database
  ini_file:
    path: /etc/neutron/neutron.conf
    section: database
    option: connection
    state: absent

- name: configure defaults
  ini_file:
    path: /etc/neutron/neutron.conf
    section: DEFAULT
    option: "{{item.option}}"
    value: "{{item.value}}"
  loop:
    - option: transport_url
      value: rabbit://{{neutron_rabbitmq_user}}:{{neutron_rabbitmq_user_password}}@{{neutron_rabbitmq_host}}
    - option: auth_strategy
      value: keystone
    # https://lists.launchpad.net/yahoo-eng-team/msg56670.html
    - option: lock_path
      value: /var/lib/neutron/tmp

- name: configure keystone authtoken
  ini_file:
    path: /etc/neutron/neutron.conf
    section: keystone_authtoken
    option: "{{item.option}}"
    value: "{{item.value}}"
  loop:
    - option: www_authenticate_uri
      value: "http://{{neutron_keystone_host}}:5000"
    - option: auth_url
      value: "http://{{neutron_keystone_host}}:5000"
    - option: memcached_servers
      value: "{{neutron_memcached_host}}:11211"
    - option: auth_type
      value: password
    - option: project_domain_name
      value: default
    - option: user_domain_name
      value: default
    - option: project_name
      value: service
    - option: username
      value: neutron
    - option: password
      value: "{{neutron_user_password}}"

# self service network

- name: configure linux_bridge
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: linux_bridge
    option: physical_interface_mappings
    value: "provider:{{neutron_provider_interface}}"

- name: configure vxlan
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: vxlan
    option: "{{item.option}}"
    value: "{{item.value}}"
  loop:
    - option: enable_vxlan
      value: "true"
    - option: local_ip
      value: "{{neutron_overlay_ip_address}}"
    - option: l2_population
      value: "true"

- name: configure vxsecuritygrouplan
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: securitygroup
    option: "{{item.option}}"
    value: "{{item.value}}"
  loop:
    - option: enable_security_group
      value: "true"
    - option: firewall_driver
      value: neutron.agent.linux.iptables_firewall.IptablesFirewallDriver

- name: allow bridge filters
  sysctl:
    name: "{{item}}"
    value: "1"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: add br_netfilter kernel module
  modprobe:
    name: br_netfilter
