- name: create database
  mysql_db:
    name: neutron
    login_user: root
    login_password: "{{neutron_db_root_password}}"

- name: create database user
  mysql_user:
    name: neutron
    password: "{{neutron_db_user_password}}"
    host: "%"
    priv: "neutron.*:ALL"
    login_user: root
    login_password: "{{neutron_db_root_password}}"

- name: create user
  os_user:
    auth: "{{os_admin_auth}}"
    name: neutron
    password: "{{neutron_user_password}}"
    domain: default

- name: add admin role to user
  os_user_role:
    auth: "{{os_admin_auth}}"
    project: service
    user: neutron
    role: admin

- name: create service
  os_keystone_service:
    auth: "{{os_admin_auth}}"
    name: neutron
    description: OpenStack Networking
    service_type: network

- name: create api endpoints
  os_keystone_endpoint:
    auth: "{{os_admin_auth}}"
    region: RegionOne
    service: neutron
    endpoint_interface: "{{item}}"
    url: "http://{{inventory_hostname}}:9696"
  loop:
    - public
    - internal
    - admin

- name: configure defaults
  ini_file:
    path: /etc/neutron/metadata_agent.ini
    section: DEFAULT
    option: "{{item.option}}"
    value: "{{item.value}}"
  loop:
    - option: nova_metadata_host
      value: controller
    - option: metadata_proxy_shared_secret
      value: "{{neutron_metadata_secret}}"
