- name: setup server
  include: server.yml
  when: is_controller_node

- name: install
  yum:
    name:
      - openstack-neutron
      - openstack-neutron-ml2
      - net-tools
  when: is_controller_node or is_network_node

- name: install linuxbridge agent
  yum:
    name:
      - openstack-neutron-linuxbridge
      - ebtables
      - ipset
  when: is_network_node or is_compute_node

- name: configure
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    backup: true
  notify:
    - init neutron db
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent

- name: configure modular layer 2 plugin
  template:
    src: network_node/ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    backup: true
  notify: restart neutron-server

- name: configure layer 3 agent
  template:
    src: network_node/l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    backup: true
  notify: restart neutron-l3-agent

- name: configure dhcp agent
  template:
    src: network_node/dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
    backup: true
  notify: restart neutron-dhcp-agent

- name: configure metadata agent
  template:
    src: network_node/metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
    backup: true
  notify: restart neutron-metadata-agent

- name: configure linuxbridge agent
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    backup: true
  notify: restart neutron-linuxbridge-agent

- name: link ml2 plugin
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link

- name: add br_netfilter kernel module
  modprobe:
    name: br_netfilter
  when: is_network_node or is_compute_node

- name: allow bridge filters
  sysctl:
    name: "{{item}}"
    value: "1"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when: is_network_node or is_compute_node

- name: flush handlers
  meta: flush_handlers

- name: start and enable server
  systemd:
    name: neutron-server
    enabled: true
    state: started
  when: is_controller_node

- name: start and enable l3 agent
  systemd:
    name: neutron-l3-agent
    enabled: true
    state: started
  when: is_network_node and neutron_l3_agent

- name: start and enable metadata agent
  systemd:
    name: neutron-metadata-agent
    enabled: true
    state: started
  when: is_network_node and neutron_metadata_agent

- name: start and enable dhcp agent
  systemd:
    name: neutron-dhcp-agent
    enabled: true
    state: started
  when: is_network_node and neutron_dhcp_agent

- name: start and enable linuxbridge agent
  systemd:
    name: neutron-linuxbridge-agent
    enabled: true
    state: started
  when: is_network_node or is_compute_node
