- name: setup network node
  include: network_node.yml
  when: is_network_node

- name: install compute
  yum:
    name: 
      - openstack-neutron-linuxbridge
      - ebtables
      - ipset
  when: is_compute_node

- name: configure
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    backup: true
  notify:
    - init neutron db
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent

- name: configure linuxbridge agent
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    backup: true
  notify: restart neutron-linuxbridge-agent

- name: add br_netfilter kernel module
  modprobe:
    name: br_netfilter

- name: allow bridge filters
  sysctl:
    name: "{{item}}"
    value: "1"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: flush handlers
  meta: flush_handlers

- name: start and enable server
  systemd:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
  when: is_network_node

- name: start and enable linuxbridge agent
  systemd:
    name: neutron-linuxbridge-agent
    enabled: true
    state: started
