- name: setup controller
  include: controller.yml
  when: "'controller_nodes' in group_names"

- name: setup compute
  include_tasks: compute.yml
  when: "'compute_nodes' in group_names"

- name: allow bridge filters
  sysctl:
    name: "{{item}}"
    value: "1"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: add br_netfilter kernel module
  modprobe:
    name: br_netfilter

- name: flush handlers
  meta: flush_handlers

- name: start and enable server
  systemd:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
  when: "'controller_nodes' in group_names"

- name: start and enable linuxbridge agent
  systemd:
    name: neutron-linuxbridge-agent
    enabled: true
    state: started
