- name: install
  apt:
    name: neutron-linuxbridge-agent

- name: install
  apt:
    name: "{{item}}"
  loop:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-linuxbridge-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
  when: "'controller_nodes' in group_names"

- name: init
  block:
    - name: init database
      include_role:
        name: mariadb
        tasks_from: init_db.yml
      vars:
        db_name: neutron
        db_user: neutron
        db_user_password: "{{neutron_db_user_password}}"

    - name: init keystone
      include_role:
        name: keystone
        tasks_from: init_api.yml
      vars:
        keystone_user: neutron
        keystone_user_password: "{{neutron_user_password}}"
        keystone_service_name: neutron
        keystone_service_description: OpenStack Networking
        keystone_service_type: network
        keystone_service_url: "http://{{inventory_hostname}}:9696"
      
  when: "'controller_nodes' in group_names"

- name: configure controller
  block: 
    - name: configure main
      template:
        src: controller/conf.j2
        dest: /etc/neutron/neutron.conf
        backup: true
      notify:
        - init neutron db
        - restart neutron-server
        - restart neutron-linuxbridge-agent
        - restart neutron-dhcp-agent
        - restart neutron-metadata-agent
        - restart neutron-l3-agent

    - name: configure modular layer 2 plugin
      template:
        src: controller/ml2_conf.ini.j2
        dest: /etc/neutron/plugins/ml2/ml2_conf.ini
        backup: true
      notify: restart neutron-server

    - name: configure linuxbridge agent
      template:
        src: controller/linuxbridge_agent.ini.j2
        dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
        backup: true
      notify: restart neutron-linuxbridge-agent

    - name: configure layer 3 agent
      template:
        src: controller/l3_agent.ini.j2
        dest: /etc/neutron/l3_agent.ini
        backup: true
      notify: restart neutron-l3-agent

    - name: configure dhcp agent
      template:
        src: controller/dhcp_agent.ini.j2
        dest: /etc/neutron/dhcp_agent.ini
        backup: true
      notify: restart neutron-dhcp-agent

    - name: configure metadata agent
      template:
        src: controller/metadata_agent.ini.j2
        dest: /etc/neutron/metadata_agent.ini
        backup: true
      notify: restart neutron-metadata-agent

  when: "'controller_nodes' in group_names"

- name: configure compute
  block:
    - name: configure main
      template:
        src: compute/conf.j2
        dest: /etc/neutron/neutron.conf
        backup: true
      notify: restart neutron-linuxbridge-agent

    - name: configure linuxbridge agent
      template:
        src: compute/linuxbridge_agent.ini.j2
        dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
        backup: true
      notify: restart neutron-linuxbridge-agent

  when: "'compute_nodes' in group_names"

- name: allow bridge filters
  sysctl:
    name: "{{item}}"
    value: "1"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: add br_netfilter kernel module
  modprobe:
    name: br_netfilter

- name: flush handlers
  meta: flush_handlers
