- name: install
  yum:
    name:
    - openstack-neutron
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge
    - ebtables

- name: init database
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: neutron
    db_user: neutron
    db_user_password: "{{neutron_db_user_password}}"

- name: init keystone
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: neutron
    keystone_user_password: "{{neutron_user_password}}"
    keystone_service_name: neutron
    keystone_service_description: OpenStack Networking
    keystone_service_type: network
    keystone_service_url: "http://{{ansible_nodename}}:9696"

- name: configure modular layer 2 plugin
  template:
    src: network_node/ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    backup: true
  notify: restart neutron-server

- name: configure layer 3 agent
  template:
    src: network_node/l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    backup: true
  notify: restart neutron-l3-agent

- name: configure dhcp agent
  template:
    src: network_node/dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
    backup: true
  notify: restart neutron-dhcp-agent

- name: configure metadata agent
  template:
    src: network_node/metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
    backup: true
  notify: restart neutron-metadata-agent

- name: link ml2 plugin
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link
