- name: configure layer 3 agent
  template:
    src: network_node/l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    backup: true
  when: neutron_l3_agent
  notify: restart neutron-l3-agent

- name: configure dhcp agent
  template:
    src: network_node/dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
    backup: true
  when: neutron_dhcp_agent
  notify: restart neutron-dhcp-agent

- name: configure metadata agent
  template:
    src: network_node/metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
    backup: true
  when: neutron_metadata_agent
  notify: restart neutron-metadata-agent

- name: configure bgp agent
  template:
    src: network_node/bgp_dragent.ini.j2
    dest: /etc/neutron/bgp_dragent.ini
    backup: true
  when: neutron_bgp and neutron_bgp_router_id
  notify: restart neutron-bgp-dragent

- name: install libreswan for vpnaas plugin
  package:
    name: libreswan
    state: "{{package_state | default('present')}}"
  when: neutron_vpnaas
