- name: install
  yum:
    name: 
      - openstack-neutron-linuxbridge
      - ebtables
      - ipset

- name: configure main
  template:
    src: compute/neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    backup: true
  notify: restart neutron-linuxbridge-agent

- name: configure linuxbridge agent
  template:
    src: compute/linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    backup: true
  notify: restart neutron-linuxbridge-agent
