- name: install
  yum:
    name:
    - openstack-neutron
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge
    - ebtables
    - net-tools

- name: init database
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: neutron
    db_user: neutron
    db_user_password: "{{neutron_db_user_password}}"

- name: init keystone
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: neutron
    keystone_user_password: "{{neutron_user_password}}"
    keystone_service_name: neutron
    keystone_service_description: OpenStack Networking
    keystone_service_type: network
    keystone_service_url: "http://{{ansible_nodename}}:9696"
