- name: create ca directory
  file:
    name: "{{item}}"
    state: directory
  loop:
    - "{{ca_dir}}"
    - "{{ca_dir}}/private"
    - "{{ca_dir}}/certs"
    - "{{ca_dir}}/csr"

- name: fetch ca certificate
  slurp:
    path: "{{ca_cert_path}}"
  register: ca_cert
  delegate_to: "{{ca_host}}"

- name: distribute ca certificate
  copy:
    content: "{{ca_cert.content | b64decode}}"
    dest: "{{ca_dir}}/certs/ca.crt"

- name: copy ca certificate to trust anchors
  copy:
    content: "{{ca_cert.content | b64decode}}"
    dest: /etc/pki/ca-trust/source/anchors/ca.crt
  when: ca_install_trust | bool

- name: update ca trust
  shell: update-ca-trust extract
  when: ca_install_trust | bool

- name: install cfssl
  get_url:
    url: "{{item.url}}"
    dest: "/usr/local/bin/{{item.name}}"
    mode: "0755"
  loop:
    - url: "{{ca_cfssl_url}}"
      name: cfssl
    - url: "{{ca_cfssljson_url}}"
      name: cfssljson
  when: ca_cfssl_install | bool
