octavia_db_user_password: "{{secrets_octavia_dbpass}}"
octavia_user_password: "{{secrets_octavia_pass}}"
octavia_rabbitmq_user: openstack
octavia_rabbitmq_user_password: "{{secrets_rabbit_pass}}"
octavia_amphora_ca_dir: /etc/pki/octavia-amphora
octavia_amphora_ca_key_passphrase: "{{secrets_octavia_amphora_ca_key_pass}}"
# use service project id here
octavia_amphora_image_project_id: f59382db809c43139982ca4189404650
octavia_management_subnet: 172.31.255.0/24
octavia_management_fixed_ip: 172.31.255.2

octavia_keystone_auth:
  auth_url: "{{keystone_url}}/v3"
  username: octavia
  password: "{{octavia_user_password}}"
  user_domain_name: Default
  project_domain_name: Default
  project_name: service

octavia_url: "http://{{ansible_nodename}}:9876"
