- name: init database
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: placement
    db_user: placement
    db_user_password: "{{placement_db_user_password}}"

- name: init keystone
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: placement
    keystone_user_password: "{{placement_user_password}}"
    keystone_service_name: placement
    keystone_service_description: Placement API
    keystone_service_type: placement
    keystone_service_url: "{{placement_url}}"

- name: install
  package:
    name:
      - openstack-placement-api
      - "{{'python' if ansible_distribution_major_version|int < 8 else 'python3'}}-osc-placement"
    state: "{{package_state | default('present')}}"
  notify:
    - init placement db
    - restart httpd

- name: configure
  template:
    src: placement.conf.j2
    dest: /etc/placement/placement.conf
    backup: true
  notify:
    - init placement db
    - restart httpd

- name: configure httpd
  template:
    src: httpd_placement-api.conf.j2
    dest: /etc/httpd/conf.d/00-placement-api.conf
  notify: restart httpd

- name: flush handlers
  meta: flush_handlers
