# this can be called by other roles to create their databases
# following variables must be defined to do that: db_name, db_user, db_user_password

- name: "create database {{db_name}}"
  mysql_db:
    name: "{{db_name}}"
    login_user: root
    login_password: "{{mariadb_root_password}}"
    login_host: "{{mariadb_bind_address}}"
  delegate_to: "{{db_host}}"

- name: "create database user {{db_user}}"
  mysql_user:
    name: "{{db_user}}"
    password: "{{db_user_password}}"
    host: "%"
    priv: "{{db_user}}.*:ALL"
    login_user: root
    login_password: "{{mariadb_root_password}}"
    login_host: "{{mariadb_bind_address}}"
  delegate_to: "{{db_host}}"
  when: db_user is defined and db_user_password is defined
