- name: install
  apt:
    name: "{{item}}"
  loop:
    - mariadb-server
    - python-pymysql
    - python-mysqldb

- name: configure
  template:
    src: openstack.cfg.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
  notify: restart mariadb

- name: set root password
  mysql_user:
    user: root
    password: "{{mariadb_root_password}}"
    host: localhost

- name: delete anonymous users
  mysql_user:
    user: ""
    host: "{{item}}"
    state: absent
  loop:
    - "{{ansible_fqdn}}"
    - localhost

- name: deny remote root access
  mysql_user:
    user: root
    password: "{{mariadb_root_password}}"
    host: "{{item}}"
  loop:
    - "::1"
    - "127.0.0.1"
    - localhost
    - "{{ansible_fqdn}}"

- name: remove test database
  mysql_db:
    db: test
    state: absent

- name: enable
  systemd:
    name: mysql
    enabled: true

- name: flush handlers
  meta: flush_handlers
