- name: install
  package:
    name:
      - mariadb
      - mariadb-server
      - "{{'python2' if ansible_distribution_major_version|int < 8 else 'python3'}}-PyMySQL"

- name: start and enable
  systemd:
    name: mariadb
    state: started
    enabled: true

- name: secure installation
  import_tasks: secure_installation.yml

- name: configure
  template:
    src: openstack.cfg.j2
    dest: /etc/my.cnf.d/openstack.cnf
  notify: restart mariadb

- name: flush handlers
  meta: flush_handlers
