- name: install
  package:
    name:
      - mariadb 
      - mariadb-server 
      - python2-PyMySQL

- name: start and enable
  systemd:
    name: mariadb
    state: started
    enabled: true
  register: mariadb_first_start

- name: secure installation
  include_tasks: secure_installation.yml
  when: mariadb_first_start.changed

- name: configure
  template:
    src: openstack.cfg.j2
    dest: /etc/my.cnf.d/openstack.cnf
  notify: restart mariadb

- name: flush handlers
  meta: flush_handlers
