- name: set root password
  mysql_user:
    user: root
    password: "{{mariadb_root_password}}"
    host_all: true
  no_log: true

- name: delete anonymous users
  mysql_user:
    login_password: "{{mariadb_root_password}}"
    user: ""
    state: absent
    host_all: true
  no_log: true

- name: remove test database
  mysql_db:
    login_password: "{{mariadb_root_password}}"
    db: test
    state: absent
  no_log: true
