- name: install
  yum:
    name: etcd

- name: configure
  template:
    src: etcd.j2
    dest: /etc/etcd/etcd.conf
  notify: restart etcd

- name: start and enable
  systemd:
    name: etcd
    enabled: true

- name: flush handlers
  meta: flush_handlers
