- name: install
  apt:
    name: etcd

- name: configure
  template:
    src: etcd.j2
    dest: /etc/default/etcd
  notify: restart etcd

- name: enable
  systemd:
    name: etcd
    enabled: true

- name: flush handlers
  meta: flush_handlers
