- name: install rbd requirements
  yum:
    name:
    - python-rbd
    - python-rados
    - ceph-common

- name: check ceph keyring
  file:
    path: "{{glance_rbd_keyring_conf}}"
    mode: 0640
    group: glance
