- name: install rbd requirements
  package:
    name:
      - "{{'python' if ansible_distribution_major_version|int < 8 else 'python3'}}-rbd"
      - "{{'python' if ansible_distribution_major_version|int < 8 else 'python3'}}-rados"
      - ceph-common

- name: add user to ceph group
  user:
    name: glance
    groups: ceph
    append: true
