- name: download
  unarchive:
    src: "https://github.com/grafana/loki/releases/download/v{{loki_version}}/loki-linux-amd64.zip"
    remote_src: true
    dest: /tmp

- name: copy binaries
  copy:
    src: /tmp/loki-linux-amd64
    remote_src: true
    dest: /usr/local/bin/loki
    mode: 0755
  notify: restart loki

- name: cleanup
  file:
    path: /tmp/loki-linux-amd64
    state: absent
