- name: check for loki version
  shell: /usr/local/bin/loki --version
  register: loki_current_version
  failed_when: false
  check_mode: false
  changed_when: loki_version not in loki_current_version.stdout

- name: install
  include_tasks: install.yml
  when: loki_current_version.changed

- name: create loki data directory
  file:
    path: /var/lib/loki
    owner: loki
    group: loki
    mode: 0750
    state: directory

- name: create loki systemd service
  copy:
    src: loki.service
    dest: /etc/systemd/system/loki.service
  notify: restart loki

- name: configure loki
  template:
    src: loki.yml.j2
    dest: /etc/loki/loki.yml
  notify: restart loki

- name: flush handlers
  meta: flush_handlers

- name: start and enable loki
  systemd:
    name: loki
    state: started
    enabled: true
