- name: check for promtail version
  shell: /usr/local/bin/promtail --version
  register: promtail_current_version
  failed_when: false
  check_mode: false
  changed_when: loki_version not in promtail_current_version.stdout

- name: download promtail
  unarchive:
    src: "https://github.com/grafana/loki/releases/download/v{{loki_version}}/promtail-linux-amd64.zip"
    dest: /tmp
    remote_src: true
  when: promtail_current_version.changed

- name: install promtail
  copy:
    src: /tmp/promtail-linux-amd64
    dest: /usr/local/bin/promtail
    mode: 0755
    remote_src: true
  when: promtail_current_version.changed

- name: create promtail systemd service
  copy:
    src: promtail.service
    dest: /etc/systemd/system/promtail.service
  notify: restart promtail

- name: configure promtail
  template:
    src: promtail.yml.j2
    dest: /etc/loki/promtail.yml
  notify: restart promtail

- name: flush handlers
  meta: flush_handlers

- name: start and enable promtail
  systemd:
    name: promtail
    state: started
    enabled: true
