- name: init nova db
  shell: | 
    su -s /bin/sh -c "nova-manage api_db sync" nova
    su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova
    su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1" nova
    su -s /bin/sh -c "nova-manage db sync" nova
  args:
    warn: false

- name: discover nova hosts
  shell: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts" nova
  args:
    warn: false

- name: restart nova-api
  systemd:
    name: nova-api
    state: restarted

- name: restart nova-scheduler
  systemd:
    name: nova-scheduler
    state: restarted

- name: restart nova-conductor
  systemd:
    name: nova-conductor
    state: restarted

- name: restart nova-novncproxy
  systemd:
    name: nova-novncproxy
    state: restarted

- name: restart nova-consoleauth
  systemd:
    name: nova-consoleauth
    state: restarted

- name: restart nova-compute
  systemd:
    name: nova-compute
    state: restarted
