- name: init nova db
  shell: | 
    su -s /bin/sh -c "nova-manage api_db sync" nova
    su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova
    su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1" nova
    su -s /bin/sh -c "nova-manage db sync" nova
  args:
    warn: false
  when: is_controller_node

- name: discover nova hosts
  shell: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts" nova
  args:
    warn: false
  when: is_controller_node

- name: restart nova-api
  systemd:
    name: openstack-nova-api
    state: restarted
  when: is_controller_node

- name: restart nova-scheduler
  systemd:
    name: openstack-nova-scheduler
    state: restarted
  when: is_controller_node

- name: restart nova-conductor
  systemd:
    name: openstack-nova-conductor
    state: restarted
  when: is_controller_node

- name: restart nova-novncproxy
  systemd:
    name: openstack-nova-novncproxy
    state: restarted
  when: is_controller_node

- name: restart nova-compute
  systemd:
    name: openstack-nova-compute
    state: restarted
  when: is_compute_node
