- name: init nova db
  shell: |
    set -e
    su -s /bin/sh -c "nova-manage api_db sync" nova
    su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova
    su -s /bin/sh -c "if ! nova-manage cell_v2 list_cells | grep -q cell1; then nova-manage cell_v2 create_cell --name=cell1; fi" nova
    su -s /bin/sh -c "nova-manage db sync" nova
  when: is_controller_node

- name: discover nova hosts
  shell: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts" nova
  when: is_controller_node

- name: restart nova-api
  systemd:
    name: openstack-nova-api
    state: restarted
  when: is_controller_node

- name: restart nova-scheduler
  systemd:
    name: openstack-nova-scheduler
    state: restarted
  when: is_controller_node

- name: restart nova-conductor
  systemd:
    name: openstack-nova-conductor
    state: restarted
  when: is_controller_node

- name: restart nova-novncproxy
  systemd:
    name: openstack-nova-novncproxy
    state: restarted
  when: is_controller_node

- name: restart nova-compute
  systemd:
    name: openstack-nova-compute
    state: restarted
  when: is_compute_node

- name: restart libvirtd
  systemd:
    name: libvirtd
    state: restarted
  when: is_compute_node

- name: define nova ceph secret
  shell: |
    virsh secret-define --file /etc/ceph/libvirt_nova_ceph.xml
    virsh secret-set-value --secret {{nova_rbd_secret_uuid}} --base64 {{nova_rbd_client_key.content | b64decode | regex_search('[A-Za-z0-9\/+]+==', multiline=True)}}
