- name: init keystone db
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
  args:
    warn: false
  
- name: init keystone token provider
  shell: |
    keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
    keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- name: bootstrap keystone
  shell: |
    keystone-manage bootstrap --bootstrap-password {{keystone_admin_password}} \
      --bootstrap-admin-url {{keystone_admin_url}}/v3/ \
      --bootstrap-internal-url {{keystone_url}}/v3/ \
      --bootstrap-public-url {{keystone_public_url}}/v3/ \
      --bootstrap-region-id {{keystone_bootstrap_region}}
