neutron_db_user_password: "{{secrets_neutron_dbpass}}"
neutron_user_password: "{{secrets_neutron_pass}}"
neutron_provider_flat_networks: []
  # - name: provider1
  #   interface: eth0
neutron_provider_vlan_networks: []
  # - name: provider1
  #   interface: eth0
  #   vlan_range: 1:10
neutron_overlay_ip_address: "{{management_ipv4.address}}"
neutron_metadata_secret: "{{secrets_metadata_secret}}"
neutron_rabbitmq_user: openstack
neutron_rabbitmq_user_password: "{{secrets_rabbit_pass}}"
neutron_nova_user: nova
neutron_nova_user_password: "{{secrets_nova_pass}}"
# selinux needs to be disabled for l3 ha, until openstack-selinux-0.8.20 is released
neutron_l3_ha: false
neutron_path_mtu: null
neutron_default_availability_zones: nova
neutron_dns_domain: openstacklocal
neutron_dnsmasq_local_resolv: false
# more information at: https://docs.openstack.org/neutron/latest/admin/config-az.html
neutron_az_aware_scheduler: false
# activate extension drivers such as `dns` here
neutron_ml2_extension_drivers: []

neutron_url: "http://{{ansible_nodename}}:9696"
neutron_nova_metadata_host: "{{ansible_nodename}}"
