- name: install
  yum:
    name:
      - httpd
      - mod_ssl

- name: request certificate
  include_role:
    name: ca
    tasks_from: req_cert.yml
  vars:
    req_name: HTTP
    req_common_name: "{{ansible_nodename}}"
    req_owner: apache
    req_group: apache
    req_post_command: systemctl reload httpd

- name: configure
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: "ServerName {{ansible_nodename}}"
    regexp: '^ServerName '
  notify: reload httpd

- name: configure ssl
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: "^{{item.regexp}}"
    line: "{{item.line}}"
  loop:
    - regexp: SSLCertificateFile 
      line: "SSLCertificateFile {{req_cert_path}}"
    - regexp: SSLCertificateKeyFile 
      line: "SSLCertificateKeyFile {{req_privatekey_path}}"
    - regexp: "RewriteEngine"
      line: "RewriteEngine On"
    - regexp: "RewriteCond"
      line: 'RewriteCond %{HTTPS} !=on'
    - regexp: "RewriteRule"
      line: 'RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]'
  notify: reload httpd

- name: create landing page
  copy:
    src: index.html
    dest: /usr/share/httpd/noindex/index.html

- name: flush handlers
  meta: flush_handlers

- name: start and enable
  systemd:
    name: httpd
    state: started
    enabled: true
