# downloads and extracts binary archives from github
# required vars on include: download_url, download_folder, download_binaries

- name: "install {{download_binaries[0]}}: download"
  unarchive:
    src: "{{download_url}}"
    remote_src: true
    dest: /tmp

- name: "install {{download_binaries[0]}}: copy binaries"
  copy:
    src: "/tmp/{{download_folder}}/{{item}}"
    remote_src: true
    dest: "/usr/local/bin/{{item}}"
    mode: 0755
  loop: "{{download_binaries}}"

- name: "install {{download_binaries[0]}}: cleanup"
  file:
    path: "/tmp/{{download_folder}}"
    state: absent
