grafana_dashboards:
  - name: Node Exporter
    url: https://grafana.com/api/dashboards/1860/revisions/23/download
  - name: OpenStack Exporter
    url: https://grafana.com/api/dashboards/14854/revisions/7/download
grafana_additional_dashboards: []
  # - folder: Ceph
  #   dashboards:
  #     - name: Ceph Cluster
  #       url: https://raw.githubusercontent.com/ceph/ceph/master/monitoring/ceph-mixin/dashboards_out/ceph-cluster.json
grafana_root_url: "https://{{ansible_nodename}}/grafana"
grafana_plugins: []
