cinder_user_password: "{{secrets_cinder_pass}}"
cinder_db_user_password: "{{secrets_cinder_dbpass}}"
cinder_rabbitmq_user: openstack
cinder_rabbitmq_user_password: "{{secrets_rabbit_pass}}"
cinder_ip_address: "{{management_ipv4.address}}"
cinder_backend: lvm # lvm and rbd are supported
cinder_lvm_pools: []
  # - name: ssd
  #   members:
  #     - /dev/sdb
cinder_rbd_pools: []
  # - name: volumes
  #   pool: volumes
cinder_rbd_ceph_conf: /etc/ceph/ceph.conf
cinder_rbd_keyring_conf: /etc/ceph/ceph.client.cinder.keyring
cinder_rbd_user: cinder
cinder_rbd_secret_uuid: 095B52A9-EAA7-4472-AF32-99F75F1F3A90
cinder_backup_driver: "" # nfs is supported
cinder_backup_nfs_share: 192.168.1.1:/mnt/cinder-backup
cinder_backup_nfs_options: ""

cinder_host: "{{hostvars[groups.controller_nodes[0]].ansible_nodename}}"
