cinder_user_password: "{{secrets_cinder_pass}}"
cinder_db_user_password: "{{secrets_cinder_dbpass}}"
cinder_rabbitmq_user: openstack
cinder_rabbitmq_user_password: "{{secrets_rabbit_pass}}"
cinder_ip_address: "{{management_ipv4.address}}"
cinder_default_availability_zone: "{{os_availability_zone}}"
cinder_default_volume_type: "__DEFAULT__"
cinder_allow_availability_zone_fallback: false
cinder_verify_glance_signatures: disabled
cinder_backends: [] # lvm, rbd and nfs are supported
# see https://docs.openstack.org/cinder/ussuri/install/cinder-storage-install-rdo.html for how to use the filter
cinder_lvm_filter: '"a|^/dev/sd[a-z][0-9]$|", "r/.*/"'
cinder_lvm_iscsi_ip_address: null
cinder_lvm_pools: []
  # - name: local-ssd
  #   vg: cinder-volumes
cinder_rbd_pools: []
  # - name: volumes
  #   pool: volumes
cinder_rbd_ceph_conf: /etc/ceph/ceph.conf
cinder_rbd_keyring: /etc/ceph/ceph.client.cinder.keyring
cinder_rbd_user: cinder
cinder_rbd_secret_uuid: 095B52A9-EAA7-4472-AF32-99F75F1F3A90
cinder_nfs_shares: []
  # - name: nas
  #   host: nas.example.com
  #   share_path: /mnt/tank/cinder
cinder_nfs_mount_options: null
cinder_backup_driver: null # nfs and rbd is supported
cinder_backup_nfs_share: 192.168.1.1:/mnt/cinder-backup
cinder_backup_nfs_options: null
cinder_backup_rbd_ceph_conf: /etc/ceph/ceph.conf
cinder_backup_rbd_keyring: /etc/ceph/ceph.client.cinder-backup.keyring
cinder_backup_rbd_user: cinder-backup
cinder_backup_rbd_pool: backups

cinder_url: "http://{{ansible_nodename}}:8776"
