- name: init cinder db
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder
  args:
    warn: false
  when: is_controller_node

- name: define cinder ceph secret
  shell: |
    virsh secret-define --file /etc/ceph/libvirt_cinder_ceph.xml
    virsh secret-set-value --secret {{cinder_rbd_secret_uuid}} --base64 {{cinder_rbd_client_key.content | b64decode | regex_search('[A-Za-z0-9\/+]+==', multiline=True)}}
  args:
    warn: false

- name: restart cinder-api
  systemd:
    name: openstack-cinder-api
    state: restarted
  when: is_controller_node

- name: restart cinder-scheduler
  systemd:
    name: openstack-cinder-scheduler
    state: restarted
  when: is_controller_node

- name: restart cinder-volume
  systemd:
    name: openstack-cinder-volume
    state: restarted
  when: is_block_storage_node

- name: restart cinder-backup
  systemd:
    name: openstack-cinder-backup
    state: restarted
  when: is_block_storage_node
        and cinder_backup_driver != ''

- name: restart target
  systemd:
    name: target
    state: restarted
