- name: init cinder db
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder
  args:
    warn: false

- name: restart cinder-scheduler
  systemd:
    name: openstack-cinder-scheduler
    state: restarted

- name: restart cinder-volume
  systemd:
    name: openstack-cinder-volume
    state: restarted

- name: restart target
  systemd:
    name: target
    state: restarted

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
