- name: init database
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: keystone
    db_user: keystone
    db_user_password: "{{keystone_db_user_password}}"

- name: install
  package:
    name:
    - openstack-keystone
    - httpd
    - "{{ '' if ansible_distribution_major_version|int < 8 else 'python3-' }}mod_wsgi"
    - mod_ssl
    state: "{{package_state | default('present')}}"
  notify:
    - init keystone db
    - restart httpd

- name: configure
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
    backup: true
  notify:
    - init keystone db
    - init keystone token provider
    - bootstrap keystone
  
- name: create directory for domain configurations
  file:
    path: /etc/keystone/domains
    state: directory
    group: keystone
    mode: 0750

- name: configure freeipa domain
  template:
    src: keystone.freeipa.conf.j2
    dest: /etc/keystone/domains/keystone.{{keystone_freeipa.domain}}.conf
    group: keystone
    mode: 0640
  when: keystone_freeipa.enabled
  notify: bootstrap keystone

- name: flush handlers
  meta: flush_handlers

- name: request certificate
  include_role:
    name: ca
    tasks_from: req_cert.yml
  vars:
    req_name: keystone
    req_common_name: "{{ansible_nodename}}"
    req_owner: apache
    req_group: apache
    req_post_command: systemctl reload httpd

- name: configure httpd virtual host
  template:
    src: wsgi-keystone.conf.j2
    dest: /etc/httpd/conf.d/wsgi-keystone.conf
  notify: restart httpd

- name: flush handlers
  meta: flush_handlers

- name: create env file for debugging
  template:
    src: admin-openrc.j2
    dest: ~/admin-openrc
    mode: 0600
  become: false

- name: create service project
  os_project:
    auth: "{{keystone_admin_auth}}"
    name: service
    description: Service Project
    domain: default

- name: create freeipa domain
  os_keystone_domain:
    auth: "{{keystone_admin_auth}}"
    name: "{{keystone_freeipa.domain}}"
    description: "FreeIPA {{keystone_freeipa.domain}}"
  when: keystone_freeipa.enabled
