- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: restart prometheus-openstack-exporter
  systemd:
    name: prometheus-openstack-exporter
    state: restarted
    daemon_reload: true
