- name: install
  apt:
    name: "{{item}}"
  loop:
    - memcached
    - python-memcache

- name: configure
  lineinfile:
    path: /etc/memcached.conf
    line: "-l {{memcached_listen_ip}}"
    regexp: '^-l '
  notify: restart memcached

- name: enable
  systemd:
    name: memcached
    enabled: true

- name: flush handlers
  meta: flush_handlers
