- name: install
  package:
    name:
      - memcached
      - python-memcached

- name: configure
  lineinfile:
    path: /etc/sysconfig/memcached
    line: "OPTIONS=\"-l 127.0.0.1,::1,{{memcached_listen_ip}}\""
    regexp: '^OPTIONS='
  notify: restart memcached

- name: flush handlers
  meta: flush_handlers

- name: start and enable
  systemd:
    name: memcached
    state: started
    enabled: true
