# NOTE: not compatible with ceph-ansible
- name: set backup keyring in ceph config
  blockinfile:
    path: /etc/ceph/ceph.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - cinder-backup"
    block: |
      [client.cinder-backup]
      keyring = {{cinder_backup_rbd_keyring}}

- name: add user to ceph group
  user:
    name: cinder
    groups: ceph
    append: true
