- name: init heat db
  shell: su -s /bin/sh -c "heat-manage db_sync" heat
  args:
    warn: false

- name: restart heat-api
  systemd:
    name: openstack-heat-api
    state: restarted

- name: restart heat-api-cfn
  systemd:
    name: openstack-heat-api-cfn
    state: restarted

- name: restart heat-engine
  systemd:
    name: openstack-heat-engine
    state: restarted

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
