- name: init heat db
  shell: su -s /bin/sh -c "heat-manage db_sync" heat
  args:
    warn: false

- name: restart heat-api
  systemd:
    name: heat-api
    state: restarted

- name: restart heat-api-cfn
  systemd:
    name: heat-api-cfn
    state: restarted

- name: restart heat-engine
  systemd:
    name: heat-engine
    state: restarted

- name: restart apache2
  systemd:
    name: apache2
    state: restarted
