- name: install compute
  yum:
    name: openstack-nova-compute

- name: configure compute
  template:
    src: compute.conf.j2
    dest: /etc/nova/nova.conf
    backup: true
  notify: restart nova-compute

- name: start and enable
  systemd:
    name: openstack-nova-compute
    enabled: true
    state: started
