- name: create databases
  mysql_db:
    name: "{{item}}"
    login_user: root
    login_password: "{{nova_db_root_password}}"
  loop:
    - nova_api
    - nova
    - nova_cell0
    - placement

- name: create database user
  mysql_user:
    name: nova
    password: "{{nova_db_user_password}}"
    host: "%"
    priv: "nova_api.*:ALL/nova.*:ALL/nova_cell0.*:ALL"
    login_user: root
    login_password: "{{nova_db_root_password}}"

- name: create placement database user
  mysql_user:
    name: placement
    password: "{{nova_db_placement_user_password}}"
    host: "%"
    priv: "placement.*:ALL"
    login_user: root
    login_password: "{{nova_db_root_password}}"

- name: create user
  os_user:
    auth: "{{os_admin_auth}}"
    name: nova
    password: "{{nova_user_password}}"
    domain: default

- name: add admin role to user
  os_user_role:
    auth: "{{os_admin_auth}}"
    project: service
    user: nova
    role: admin

- name: create service
  os_keystone_service:
    auth: "{{os_admin_auth}}"
    name: nova
    description: OpenStack Compute
    service_type: compute

- name: create api endpoints
  os_keystone_endpoint:
    auth: "{{os_admin_auth}}"
    region: RegionOne
    service: nova
    endpoint_interface: "{{item}}"
    url: "http://{{inventory_hostname}}:8774/v2.1"
  loop:
    - public
    - internal
    - admin

- name: create placement user
  os_user:
    auth: "{{os_admin_auth}}"
    name: placement
    password: "{{nova_placement_user_password}}"
    domain: default

- name: add admin role to placement user
  os_user_role:
    auth: "{{os_admin_auth}}"
    project: service
    user: placement
    role: admin

- name: create placement service
  os_keystone_service:
    auth: "{{os_admin_auth}}"
    name: placement
    description: Placement API
    service_type: placement

- name: create placement api endpoints
  os_keystone_endpoint:
    auth: "{{os_admin_auth}}"
    region: RegionOne
    service: placement
    endpoint_interface: "{{item}}"
    url: "http://{{inventory_hostname}}:8778"
  loop:
    - public
    - internal
    - admin
