- name: create databases
  include_role:
    name: mariadb
    tasks_from: init_db.yml
  vars:
    db_name: "{{item}}"
  loop:
    - nova_api
    - nova
    - nova_cell0

- name: create database user
  mysql_user:
    name: nova
    password: "{{nova_db_user_password}}"
    host: "%"
    priv: "nova_api.*:ALL/nova.*:ALL/nova_cell0.*:ALL"
    login_user: root
    login_password: "{{db_root_password}}"
    login_host: "{{mariadb_bind_address}}"
  delegate_to: "{{db_host}}"
  run_once: true
  no_log: true

- name: init keystone nova
  include_role:
    name: keystone
    tasks_from: init_auth.yml
  vars:
    keystone_user: nova
    keystone_user_password: "{{nova_user_password}}"
    keystone_service_name: nova
    keystone_service_description: OpenStack Compute
    keystone_service_type: compute
    keystone_service_url: "{{nova_url}}"
    keystone_service_path: /v2.1

- name: install controller
  package:
    name:
      - openstack-nova-api
      - openstack-nova-conductor
      - openstack-nova-novncproxy
      - openstack-nova-scheduler
    state: "{{package_state | default('present')}}"
  notify:
    - init nova db
    - restart nova-api
    - restart nova-scheduler
    - restart nova-conductor
    - restart nova-novncproxy

- name: request certificate
  include_role:
    name: ca
    tasks_from: req_cert.yml
  vars:
    req_name: nova-novnc
    req_common_name: "{{ansible_nodename}}"
    req_owner: nova
    req_group: nova
    req_post_command: systemctl restart openstack-nova-novncproxy
    req_notify: restart nova-novncproxy

- name: create libvirt-vnc ca
  include_role:
    name: ca
    tasks_from: create_ca.yml
  vars:
    ca_dir: "{{nova_libvirt_vnc_ca_dir}}"
    ca_organization_unit_name: libvirt VNC
    ca_owner: root
    ca_key_passphrase: "{{nova_libvirt_vnc_ca_key_passphrase}}"
  when: nova_libvirt_vnc_tls

- name: request libvirt-vnc certificate for nova-novnc
  include_role:
    name: ca
    tasks_from: request_cert.yml
  vars:
    ca_dir: "{{nova_libvirt_vnc_ca_dir}}"
    ca_organization_unit_name: libvirt VNC
    ca_key_passphrase: "{{nova_libvirt_vnc_ca_key_passphrase}}"
    req_name: nova-novnc
    req_common_name: "{{ansible_nodename}}"
    req_owner: nova
    req_group: nova
    req_post_command: systemctl restart openstack-nova-novncproxy
    req_notify: restart nova-novncproxy
  when: nova_libvirt_vnc_tls
