- name: configure database connection
  ini_file:
    path: /etc/nova/nova.conf
    section: "{{item.section}}"
    option: connection
    value: "mysql+pymysql://{{item.db_user}}:{{item.db_pass}}@{{nova_db_host}}/{{item.db_name}}"
  loop:
    - section: api_database
      db_name: nova_api
      db_user: nova
      db_pass: "{{nova_db_user_password}}"
    - section: database
      db_name: nova
      db_user: nova
      db_pass: "{{nova_db_user_password}}"
    - section: placement_database
      db_name: placement
      db_user: placement
      db_pass: "{{nova_db_placement_user_password}}"
  notify: init nova db

- name: configure neutron
  ini_file:
    path: /etc/nova/nova.conf
    section: neutron
    option: "{{item.option}}"
    value: "{{item.value}}"
  loop:
    - option: url
      value: "http://{{nova_neutron_host}}:9696"
    - option: auth_url
      value: "http://{{nova_keystone_host}}:5000"
    - option: auth_type
      value: password
    - option: project_domain_name
      value: default
    - option: user_domain_name
      value: default
    - option: region_name
      value: RegionOne
    - option: project_name
      value: service
    - option: username
      value: neutron
    - option: password
      value: "{{nova_neutron_user_password}}"
    - option: service_metadata_proxy
      value: "true"
    - option: metadata_proxy_shared_secret
      value: "{{nova_metadata_secret}}"

- name: configure vnc
  ini_file:
    path: /etc/nova/nova.conf
    section: vnc
    option: "{{item.option}}"
    value: "{{item.value}}"
  loop:
    - option: enabled
      value: "true"
    - option: server_listen
      value: "$my_ip"
    - option: server_proxyclient_address
      value: "$my_ip"

- name: enable
  systemd:
    name: "{{item}}"
    enabled: true
  loop:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
