- name: setup controller
  include: controller.yml
  when: "'controller_nodes' in group_names"

- name: setup compute
  include_tasks: compute.yml
  when: "'compute_nodes' in group_names"

- name: flush handlers
  meta: flush_handlers
