- name: setup controller
  include: controller.yml
  when: is_controller_node

- name: install compute
  yum:
    name: openstack-nova-compute
  when: is_compute_node

- name: configure
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    backup: true
  notify:
    - init nova db
    - restart nova-api
    - restart nova-scheduler
    - restart nova-conductor
    - restart nova-novncproxy
    - restart nova-compute

- name: configure kvm
  copy:
    src: kvm.conf
    dest: /etc/modprobe.d/kvm.conf
  when: "is_compute_node
        and nova_nested_guest_support | bool"

- name: configure rbd ephemeral storage backend
  include_tasks: rbd.yml
  when: "is_compute_node
        and nova_ephemeral_storage_backend == 'rbd'"

- name: flush handlers
  meta: flush_handlers

- name: start and enable controller
  systemd:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy
  when: is_controller_node

- name: start and enable compute
  systemd:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - libvirtd
    - openstack-nova-compute
  when: is_compute_node

- name: add flavors
  os_nova_flavor:
    auth: "{{keystone_admin_auth}}"
    name: "{{item.name}}"
    vcpus: "{{item.vcpus}}"
    ram: "{{item.ram}}"
    disk: "{{item.disk}}"
  loop: "{{nova_flavors}}"
  run_once: true
