- name: create ssh directories
  file:
    path: "{{item.ssh_dir}}"
    state: directory
    mode: 0700
    owner: "{{item.owner}}"
  loop:
    - ssh_dir: /root/.ssh
      owner: root
    - ssh_dir: /var/lib/nova/.ssh
      owner: nova

- name: create ssh key pair
  openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519
    mode: 0600

- name: copy ssh key pair for nova
  copy:
    src: /root/.ssh/id_ed25519
    remote_src: true
    dest: /var/lib/nova/.ssh/id_ed25519
    owner: nova
    mode: 0600

- name: fetch ssh host keys
  command: "ssh-keyscan {{ansible_nodename}}"
  changed_when: false
  check_mode: false
  register: nova_ssh_host_key

- name: fetch ssh public keys
  slurp:
    path: /root/.ssh/id_ed25519.pub
  register: nova_ssh_public_key

- name: set authorized keys
  template:
    src: authorized_keys.j2
    dest: "{{item.ssh_dir}}/authorized_keys"
    mode: 0600
    owner: "{{item.owner}}"
  loop:
    - ssh_dir: /root/.ssh
      owner: root
    - ssh_dir: /var/lib/nova/.ssh
      owner: nova

- name: set known hosts
  template:
    src: known_hosts.j2
    dest: "{{item.ssh_dir}}/known_hosts"
    mode: 0644
    owner: "{{item.owner}}"
  loop:
    - ssh_dir: /root/.ssh
      owner: root
    - ssh_dir: /var/lib/nova/.ssh
      owner: nova

- name: set shell for nova user
  user:
    name: nova
    shell: /bin/bash
